F12
A-Fidele/crazee-burger pull request #15
Opened 2023-10-09 15:13 UTC by A-Fidele

2023-10-09 17:34 UTC, KentuckySato requested changes
Problème au niveau du calcul en temps réel du panier lorsqu'un produit est édité avec un nombre à virgule + suggestion de code.

2023-10-09 17:34 UTC, KentuckySato commented on src/components/pages/order/OrderPage.jsx
> +    const productClickedOn = menu.find(
```suggestion
    const productClickedOn = findObjectById()
```

2023-10-09 17:39 UTC, vileaddev requested changes
Y'a une bug donc je ne peux pas valider la PR mais aussi y'a le fichier helper

2023-10-09 17:39 UTC, vileaddev commented on src/components/pages/order/Main/Basket/BasketCards.jsx
> +  const checkProductIsClicked = (idProductedCliked, productSelected) => {
return implicite.

2023-10-09 17:39 UTC, vileaddev commented on src/components/pages/order/Main/Basket/BasketCards.jsx
> +  const checkProductIsClicked = (idProductedCliked, productSelected) => {
à mettre dans un fichier helper.

2023-10-10 05:20 UTC, vileaddev approved these changes
Superbe ! De mon côté, je valide :) Tu peux merge ta PR Aurélien 😉 ✅

2023-10-10 11:18 UTC, merged