F13
A-Fidele/crazee-burger pull request #16
Opened 2023-10-17 07:56 UTC by A-Fidele

2023-10-17 22:04 UTC, KentuckySato requested changes
Des petits détails mais rien de très grave.

2023-10-17 22:04 UTC, KentuckySato commented on src/components/pages/login/LoginForm.jsx
>    font-family: "Amatic SC", cursive;
design system

2023-10-17 22:04 UTC, KentuckySato commented on src/components/pages/order/Main/Basket/EmptyBasket.jsx
> +        {isLoading ? BASKET_MESSAGE.loading : BASKET_MESSAGE.empty}
```suggestion
        {isLoading ? BASKET_MESSAGE.LOADING : BASKET_MESSAGE.EMPTY}
```

2023-10-17 22:04 UTC, KentuckySato commented on src/components/pages/order/Main/LoadingPage.jsx
> +    font-family: "Amatic SC";
design system

2023-10-17 22:04 UTC, KentuckySato commented on src/components/pages/order/Main/LoadingPage.jsx
> +    font-family: "Amatic SC", cursive;
design system

2023-10-17 22:04 UTC, KentuckySato commented on src/components/pages/order/Main/MainRightSide/Admin/SavedEditMeessage.jsx
> +  .message {
classe à retirer ?

2023-10-17 22:04 UTC, KentuckySato commented on src/enums/product.js
> +    empty: "Votre commande est vide.",
```suggestion
    EMPTY: "Votre commande est vide.",
```

2023-10-17 22:04 UTC, KentuckySato commented on src/enums/product.js
> +    loading: "Chargement en cours..."
```suggestion
    LOADING: "Chargement en cours..."
```

2023-10-17 22:04 UTC, KentuckySato commented on src/hooks/useBasket.jsx
> +    console.log("username", username);
console.log

2023-10-23 08:19 UTC, vileaddev requested changes
Quelques petites remarques mais dans l'ensemble une bonne PR ! 👏

2023-10-23 08:19 UTC, vileaddev commented on src/api/product.js
> +  const newDoc = {
```suggestion
  const newMenu = {
```

2023-10-23 08:19 UTC, vileaddev commented on src/api/user.js
> +   const newDoc = {
```suggestion
   const newUser = {
```

2023-10-23 08:19 UTC, vileaddev commented on src/api/user.js
> + export const authentificateUser = async (userId) => {
```suggestion
 export const authenticateUser = async (userId) => {
```

2023-10-23 08:19 UTC, vileaddev commented on src/api/user.js
> +  const userExists = await getUser(userId);
```suggestion
  const existingUser = await getUser(userId);
```

2023-10-23 08:19 UTC, vileaddev commented on src/components/pages/order/helpers/userSession.js
> +   const firestoreMenu = await getMenu(username)
je valide le naming `firestoreMenu` ✅

2023-10-23 08:19 UTC, vileaddev commented on src/hooks/useMenu.jsx
> +  const handleEdit = async (productEdit) => {
```suggestion
  const handleEdit = async (productEdit, username) => {
```

2023-10-23 08:19 UTC, vileaddev commented on src/hooks/useMenu.jsx
> +  const { username } = useParams();
je préfère pas le useParams() car tu ne sais pas la valeur qu'aura le useParams() au moment où tu vas appeler le custom hook useMenu()

2023-10-23 08:23 UTC, vileaddev commented on src/api/product.js
> +  const newDoc = {
💡  Tu peux même l'appeler `menuUpdated` puisque la fonction s'appelle `updateMenuDB()`

2023-10-25 13:33 UTC, vileaddev approved these changes
Je valide ✅ 😉 Tu peux merge 👍

2023-10-25 13:33 UTC, vileaddev commented on src/components/pages/order/Main/MainRightSide/EmptyMenuAdmin.jsx
> +          onClick={onReset}
mieux oui ✅

2023-10-25 13:33 UTC, vileaddev commented on src/hooks/useMenu.jsx
> +    console.log("username: ", username);
console.log() à retirer

2023-10-25 14:07 UTC, merged